const express = require('express')
const router = express.Router()
const upload = require('../../middlewares/upload')
const controller = require("../../controllers/admin/product_controller")
router.get('/',controller.index)
router.get('/delete/:id',controller.delete)
router.get('/create',controller.create)
router.post('/create',upload.single('image'),controller.createPost)
router.get('/edit/:id',controller.edit)
router.post('/edit/:id',upload.single('image'),controller.editPost)
module.exports = router